/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: hdu                                                   *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmhdu;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorshdu[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palhdu = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _achdu[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ___XX___, ________, ________, ________,
  ________, ________, ________, ________, ___XXX__, ________, ________, ________,
  ________, ________, ________, ________, __XXXXX_, ________, ________, ________,
  ________, ________, ________, ________, __XXXXXX, ________, ____XX__, ________,
  ________, ________, ________, ________, _XXXXXXX, X_______, ___XXX__, ________,
  ________, ________, ________, ________, _XXXXXXX, XX______, __XXXXX_, ________,
  ________, ________, ____XXXX, ________, _XXXXXXX, XX______, _XXXXXX_, ________,
  ________, ________, ____XXXX, XX______, XXXXXXXX, XXX____X, XXXXXXX_, ________,
  ________, ________, ____XXXX, XXXX____, XXXXXXXX, XXXX__XX, XXXXXXX_, ________,
  ________, ________, ____XXXX, XXXXXX__, XXXXXXXX, XXXX_XXX, XXXXXXX_, ________,
  ________, ________, ___XXXXX, XXXXXXX_, XXXXXXXX, XXXX_XXX, XXXXXXXX, ________,
  ________, ________, ___XXXXX, XXXXXXXX, _XXXXXXX, XXXXX_XX, XXXXXXXX, ________,
  ________, ________, ___XXXXX, XXXXXXXX, X_XXXXXX, XXXXX_XX, XXXXXXXX, ________,
  ________, ________, ___XXXXX, XXXXXXXX, X__XXXXX, XXXXX_XX, XXXXXXXX, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XX_XXXXX, XXXXX_XX, XXXXXXXX, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXX_XXXX, XXXXX_XX, XXXXXXXX, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXX__XXX, XXXXX_XX, XXXXXXX_, ________,
  ________, ________, _______X, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXX_, ________,
  ________, ________, ________, _XXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXX_, ________,
  ________, ________, ________, ___XXXXX, XXXXX_XX, XXXXX_XX, XXXXXXX_, ________,
  ________, ________, ________, ____XXXX, XXXXX_XX, XXXXX_XX, XXXXXXX_, ________,
  ________, ________, _____XXX, X____XXX, XXXXX_XX, XXXXX_XX, XXXXXX__, ________,
  ________, ________, XXXXXXXX, XX____XX, XXXXX_XX, XXXXX_XX, XXXXXX__, ________,
  ________, _____XXX, XXXXXX__, ______XX, XXXXXXXX, XXXXX_XX, XXXXX___, ________,
  ________, ___XXXXX, XX______, _______X, XXXXXXXX, XXXX_XXX, XXXXX___, ________,
  ________, _XXXXXXX, ________, _______X, XXXXXXXX, XXXX_XXX, XXXXX___, ________,
  ________, XXXXXXX_, ________, _______X, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  _______X, XXXXX___, ________, ________, XXXXX_XX, XXXXXXXX, XXX_____, ________,
  ______XX, XXXX____, ________, ________, XXXXX_XX, XXX_XXXX, XX______, ________,
  _____XXX, XXXX____, ________, ________, XXXXX_XX, XX_XXXXX, XX______, ________,
  ____XXXX, XXXX____, ________, ________, XXXXX_XX, XX_XXXXX, X_______, ________,
  ____XXXX, XXX_____, ________, ________, XXXX_XXX, X_XXXXXX, ________, ________,
  ___XXXXX, XXX_____, ________, _______X, XXX_XXXX, _XXXXXX_, ________, ________,
  ___XXXXX, XXX_____, ________, _______X, XXX_XXXX, XXXXXX__, ________, ________,
  ___XXXXX, XXX_____, ________, _______X, XX_XXXX_, XXXXX___, ________, ________,
  ___XXXXX, XXX_____, ________, ______XX, X_XXXXXX, XXX_____, ________, ___XX___,
  ___XXXXX, XXXX____, ________, ______XX, XXXXXXXX, XX______, ________, __XX____,
  ___XXXXX, XXXX____, ________, ____XXXX, XXXXXXXX, ________, ________, _XXX____,
  ___XXXXX, XXXXX___, ________, ___XXX_X, XXXXXX__, ________, ________, XXX_____,
  ____XXXX, XXXXXX__, ________, __XXXXXX, XXXX____, ________, ______XX, XX______,
  ____XXXX, XXXXXXX_, ________, XXXXXXXX, XX______, ________, _____XXX, X_______,
  _____XXX, XXXXXXXX, X_____XX, XXXXX__X, ________, ________, ___XXXXX, ________,
  _____XXX, XXXXXXXX, XX____XX, XXX_____, ________, ________, XXXXXXX_, ________,
  ______XX, XXXXXXXX, XXXXXX__, ________, ________, ____XXXX, XXXXX___, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXX_____, _______X, XXXXXXXX, XXX_____, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________,
  ________, ________, _____XXX, XXXXXXXX, XX______, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, _XX_XXXX, _XXXX_XX, XX______, ________, ________,
  ________, ________, ________, _XX_X__X, _X____X_, ________, ________, ________,
  ________, ________, ________, _XX_XXXX, _XXXX_XX, XX______, ________, ________,
  ________, ________, ________, _XX____X, ____X_X_, _X______, ________, ________,
  ________, ________, ________, _XX_XXXX, _XXXX_XX, XX______, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmhdu = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _achdu,  // Pointer to picture data (indices)
  &_Palhdu   // Pointer to palette
};

/*************************** End of file ****************************/
