/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Service Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LCD.h>
#include <D3.h>
#include <D3_aliases.h>
#include <D4.h>
#include <D4_aliases.h>
#include <D5.h>
#include <D5_aliases.h>
#include <P0_7_SWITCH.h>
#include <P0_7_SWITCH_aliases.h>
#include <D10_P3_4.h>
#include <D10_P3_4_aliases.h>
#include <LCD_Reset.h>
#include <LCD_Reset_aliases.h>
#include <LCD_SPIM_UDB.h>
#include <LCD_SPIM_UDB_PVT.h>
#include <LCD_SCLK.h>
#include <LCD_SCLK_aliases.h>
#include <LCD_MOSI.h>
#include <LCD_MOSI_aliases.h>
#include <LCD_SS.h>
#include <LCD_SS_aliases.h>
#include <LCD_SPIM_UDB_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>

/*[]*/

